#!/bin/bash

CURR_DIR=$(pwd)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "GENERATING "${1}"_BIB.js using "${BASH_SOURCE[0]}" params="${1}" "${2}

cd $SCRIPT_DIR

DIR_IN=${2}
BIB=${1}

cp ${DIR_IN}/${1}_bib.tab .

ARCH=${BIB}_bib.tab
bash fix_no_puntuation_sh $ARCH
node print_scods_tab.js $ARCH.fix > sql3_${BIB}.tab

cd ${CURR_DIR}



