#!/bin/bash

CURR_DIR=$(pwd)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "GENERATING STRA and SOCU bibs using "${BASH_SOURCE[0]}

cd $SCRIPT_DIR

rm stra_*.tab
rm socu_*.tab

bash gen_stra_tab_sh BYZ KJVs
bash gen_stra_tab_sh BYZ RVAs
bash gen_stra_tab_sh WLC KJVs
bash gen_stra_tab_sh WLC RVAs

cd ${CURR_DIR}

