#!/bin/bash

CURR_DIR=$(pwd)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "GENERATING "${1}"_SBIB.js using "${BASH_SOURCE[0]}

cd $SCRIPT_DIR

IN_DIR="../txt_tabs"
OUT_DIR="."
SLQ_FILE="./get_SBIB_tab.sql3"

fin=${IN_DIR}/${1}_txt.tab
fout=${OUT_DIR}/${1}_sbib.tab
js_out=${OUT_DIR}/${1}_SBIB.js

echo "Generating "${fout}" from "${fin}

cp ${fin} in.tab
sed -i 's/:/|/g' in.tab

rm ${fout}
rm out.tab
sqlite3 < ${SLQ_FILE}
mv out.tab ${fout}
rm in.tab

echo "Generating "${js_out}" from "${fin}

node print_js_sbib.js ${fout} ${1}


cd ${CURR_DIR}
